name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World"

      - name: Print current date
        run: date

      - name: List directory contents
        run: ls -l
